### PR TITLE
fix required GC3Pie SVN revision, should be 4223 (fix for Core.select_resource())

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
wait, this isn't working as I expected it should...

@riccardomurri: the `__version__` value in `gc3libs/__init__.py` doesn't get updated automagically?

I'm still seeing this (with a fresh SVN checkout):

```
$ grep __version__ gc3libs/__init__.py 
__version__ = 'development version (SVN $Revision: 4218 $)'
$ svn info
Path: .
URL: http://gc3pie.googlecode.com/svn/trunk/gc3pie
Repository Root: http://gc3pie.googlecode.com/svn
Repository UUID: d0f2d5a0-84c0-18d2-3862-8add1af26540
Revision: 4231
Node Kind: directory
Schedule: normal
Last Changed Author: riccardo.murri
Last Changed Rev: 4231
Last Changed Date: 2015-06-12 18:28:54 +0200 (Fri, 12 Jun 2015)
```

**Comment by riccardomurri** [comment]
> the `__version__` value in `gc3libs/__init__.py` doesn't get updated automagically?

oh, I see the issue.  SVN updates the `$Revision` tag with the last commit in which that _file_ was updated...  to get the last commit in the repo, one has to run `svn info`.  

I'm not sure what's the best way forward.

**Comment by boegel** [comment]
Doesn't that effectively render the use of `$Revision` in `__version__` useless?

**Comment by riccardomurri** [comment]
It's the best approximation to the "repo version" number we can get in SVN.

For now, I would suggest that you check the `__version__` from module
`gc3libs.core`, which is where the fix in `select_resources` took place.
Next time you'll run a development version it will be Git anyway ;-)

**Comment by boegel** [comment]
ok, see https://github.com/gc3-uzh-ch/easybuild-framework/pull/13

**Pull request merged**
